html: &defaults
  view_format: 'html'
  search_bar: 'default'
  footmenu: 'default'
  with_layout: "application"
  css_file_name: "default"
  supports_javascript: false

capable: &capable
  <<: *defaults
  supports_javascript: true

simplehtml: &simplehtml
  <<: *defaults
  search_bar: "simple"
  footmenu: "simple"
  css_file_name: "simple"

webkit: &webkit
  <<: *capable
  search_bar: 'webkit'
  css_file_name: 'webkit'

android: 
  <<: *webkit
  css_file_name: "android"

iphone:
  <<: *webkit
  css_file_name: 'iphone'
  
iphone2:
  <<: *webkit
  css_file_name: 'iphone2'

native_iphone:
  <<: *capable
  search_bar: false

palm_pre:
  <<: *webkit
  css_file_name: 'palm_pre'

kindle2:
  <<: *defaults
  search_bar: 'kindle'
  css_file_name: "kindle"

blackberry:
  <<: *defaults
  css_file_name: "blackberry"

netfront: &netfront
  <<: *simplehtml

psp:
  <<: *netfront

ps3:
  <<: *netfront

wii:
  <<: *capable
  css_file_name: 'wii'

operamini:
  <<: *simplehtml
  css_file_name: "operamini"

wml:
  view_format: 'wml'
  search_bar: 'wml'
  supports_javascript: false
