html: &defaults
  view_format: 'html'
  search_bar: 'webkit'
  with_layout: "application"
  css_file_name: "webkit"
  supports_javascript: false

desktop: &capable
  <<: *defaults
  supports_javascript: true

webkit:
  <<: *capable
  supports_javascript: true

rhosync:
  <<: *capable
  with_layout: false
  search_bar: false
  supports_javascript: true

kindle2:
  <<: *defaults
  search_bar: 'kindle'
  css_file_name: "kindle"

blackberry:
  <<: *defaults
  css_file_name: "blackberry"

wml:
  view_format: 'wml'
  search_bar: 'wml'
  supports_javascript: false