html: &defaults
  view_format: 'html'
  search_bar: true
  css_file_name: "application"
  supports_javascript: false

desktop: &capable
  <<: *defaults
  supports_javascript: true

webkit:
  <<: *capable
  supports_javascript: true

webkit_native:
  <<: *capable
  search_bar: false
  supports_javascript: true

blackberry:
  <<: *defaults
  css_file_name: "blackberry"

wml:
  view_format: 'wml'
  search_bar: false
  supports_javascript: false