en: 
  main_page: "Main_Page"
  selectors:
    article_of_the_day: "#mp-tfa"
    news_items: "#mp-itn"
de: 
  main_page: "Wikipedia:Hauptseite"
  selectors:
    article_of_the_day: "#hauptseite-artikel .inhalt"
    news_items: "#hauptseite-nachrichten .inhalt"
fr:
  main_page: "Accueil"
  selectors:
    article_of_the_day: "#bodyContent table tr:nth-child(3) td:nth-child(3) div:nth-child(1) .accueil_contenu"
    news_items: "#bodyContent table tr:nth-child(3) td:nth-child(3) div:nth-child(3) .accueil_contenu"
jp: 
  main_page: "メインページ"
  selectors:
    article_of_the_day: "/html/body/div/div/div/div[2]/table[3]/tr/td/div"
pl: 
  main_page: "Strona_główna"
  selectors:
    article_of_the_day: "div[style='padding: 5px; font-size: 9pt;']"
    news_items: "#bodyContent :nth-child(7) :nth-child(5)"