en: 
  main_page: "Main_Page"
  translations:
    go: "Go"
    search_results: "Search Results"
    no_article_found: "No Article Found"
    featured_article: "Today's Featured Article"
    in_the_news: "In The News"
    random_article: "Random Article"
    copyright: "All text is available under the terms of the GNU Free Documentation License.\n Wikipedia® is a registered trademark of the Wikimedia Foundation, Inc., a U.S. registered 501(c)(3) tax-deductible nonprofit charity."
  selectors:
    article_of_the_day: "#mp-tfa"
    news_items: "#mp-itn"
de: 
  main_page: "Wikipedia:Hauptseite"
  translations:
    go: "Artikel"
    search_results: "Suchergebnisse"
    no_article_found: "Es existiert kein Artikel"
    featured_article: "Artikel des Tages"
    in_the_news: "In den Nachrichten"
    random_article: "Zufälliger Artikel"
    copyright: "Der Text steht unter der GNU-Lizenz für freie Dokumentation.\n Wikipedia® ist eine eingetragene Marke der Wikimedia Foundation Inc."
  selectors:
    article_of_the_day: "#hauptseite-artikel .inhalt"
    news_items: "#hauptseite-nachrichten .inhalt"
fr:
  main_page: "Accueil"
  translations:
    go: "Consulter"
    search_results: "Résultats de la recherche"
    no_article_found: "Aucun titre de page ne correspond à la recherche"
    featured_article: "Lumière sur..."
    in_the_news: "Actualités et événements"
    random_article: "Un article au hasard"
    copyright: "Droit d'auteur : Tous les textes sont disponibles sous les termes de la licence de documentation libre GNU (GFDL).
Wikipedia® est une marque déposée de la Wikimedia Foundation, Inc., organisation de bienfaisance régie par le paragraphe 501(c)(3) du code fiscal des États-Unis."
  selectors:
    article_of_the_day: "#bodyContent table tr:nth-child(3) td:nth-child(3) div:nth-child(1) .accueil_contenu"
    news_items: "#bodyContent table tr:nth-child(3) td:nth-child(3) div:nth-child(3) .accueil_contenu"
ja: 
  main_page: "メインページ"
  translations:
    go: "表示"
    search_results: "検索結果"
    no_article_found: "検索した名称のページは存在しませんでした"
    featured_article: "秀逸な記事"
    in_the_news: "新着記事"
    random_article: "つまみ読み"
    copyright: "すべてのウィキペディアの素材におけるテキストの複製、配布及び改変は、Free Software Foundationが発行するGNU Free Documentation Licenseのバージョンの1.2以上の条件の下に、許諾されます。\n Wikipedia® は Wikimedia Foundation, Inc. の米国およびその他の国における登録商標です"
  selectors:
    article_of_the_day: "#bodyContent table:nth-child(8) td:nth-child(1) div:nth-child(3)"
    news_items:         "#bodyContent table:nth-child(8) td:nth-child(1) div:nth-child(6)"
pl: 
  main_page: "Strona_główna"
  translations: 
    go: "Przejdź" 
    search_results: "Wyniki wyszukiwania"
    no_article_found: "No Article Found"
    featured_article: "Today's Featured Article"
    in_the_news: "In The News"
    random_article: "Random Article"
    copyright: "All text is available under the terms of the GNU Free Documentation License.\n Wikipedia® is a registered trademark of the Wikimedia Foundation, Inc., a U.S. registered 501(c)(3) tax-deductible nonprofit charity."
  selectors:
    article_of_the_day: "div[style='padding: 5px; font-size: 9pt;']"
    news_items: "#bodyContent :nth-child(7) :nth-child(5)"
es:
  main_page: "Wikipedia:Portada"
  translations:
    go: "Ir"
    search_results: "Resultados de la búsqueda"
    no_article_found: "No hay coincidencias"
    featured_article: "Artículo destacado"
    in_the_news: "Actualidad"
    random_article: "Página aleatoria"
    copyright: "Contenido disponible bajo los términos de la Licencia de documentación libre de GNU (véase Derechos de autor).\nWikipedia® es una marca registrada de la organización sin ánimo de lucro Wikimedia Foundation, Inc."
  selectors:
    article_of_the_day: "#bodyContent table:nth-child(6) table:nth-child(1) tr:nth-child(2)"
    news_items: "#bodyContent table:nth-child(6) table:nth-child(1) tr:nth-child(8)"
pt:
  main_page: "Página_principal"
  translations:
    go: "Ir"
    search_results: "Resultados de pesquisa"
    no_article_found: "Não Encontrado artigo"
    featured_article: "Artigo em destaque"
    in_the_news: "Eventos recentes"
    random_article: "Página aleatória"
    copyright: "O texto desta página está sob a GNU Free Documentation License. \nOs direitos autorais de todas as contribuições para a Wikipédia pertencem aos seus respectivos autores (mais informações em direitos autorais)."
  selectors:
    article_of_the_day: "#bodyContent table:nth-child(1) tr:nth-child(2)"
    news_items: "#bodyContent div table:nth-child(1) tr:nth-child(2)"
nl: 
  main_page: "Hoofdpagina"
  translations:
    go: "Artikel"
    search_results: "Zoekresultaten"
    no_article_found: "Geen resultaten gevonden"
    featured_article: "Uitgelicht"
    in_the_news: "Actueel"
    in_the_news_alt: "In het nieuws"
    random_article: "Willekeurige pagina"
    copyright: "De tekst op Wikipedia is zonder enige vorm van garantie beschikbaar onder de GNU Free Documentation License. \nWikipedia® is een geregistreerd handelsmerk van de Wikimedia Foundation, Inc., een in de Verenigde Staten geregistreerde organisatie zonder winstoogmerk."
  selectors:
    article_of_the_day: "tr:nth-child(4) table.radius:nth-child(1) tr:nth-child(3) td:nth-child(1) div:nth-child(1)"
    news_items: "tr:nth-child(4) table.radius:nth-child(2) tr:nth-child(3) td:nth-child(1) div:nth-child(1)"
    
fi:
  main_page: "Wikipedia:Etusivu"
  translations:
    go: "Siirry"
    search_results: "Etsi"
    no_article_found: "Artikkelia ei löytynyt"
    featured_article: "Suositeltu artikkeli"
    in_the_news: "Ajankohtaista"
    random_article: "Satunnainen artikkeli"
    copyright: "Teksti on käytettävissä lisenssillä GNU Free Documentation License.\n Wikipedia® on Wikimedia-säätiön rekisteröimä tavaramerkki."
  selectors:
    article_of_the_day: "#bodyContent table tr:nth-child(2) td:nth-child(1) div:nth-child(2) div:nth-child(2)"
    news_items: "#bodyContent table tr:nth-child(2) td:nth-child(2) div:nth-child(1) div:nth-child(2)"
it:
  main_page: "Pagina_principale"
  translations:
    go: "Vai"
    search_results: "Risultati della ricerca"
    no_article_found: "Nessuna corrispondenza"
    featured_article: "Vetrina"
    in_the_news: "Novità"
    random_article: "Una voce e caso"
    copyright: "Tutti i testi sono disponibili nel rispetto dei termini della GNU Free Documentation License."
  selectors:
    article_of_the_day: "#Vetrina ~ div"
    news_items: "a[id='Novit.C3.A0'] ~ div"
  
