en:
  main_page: "Main_Page"
  translations:
    go: "Go"
    search_results: "Search Results"
    no_article_found: "No Article Found"
    featured_article: "Today's Featured Article"
    in_the_news: "In The News"
    home_button: "Home"
    random_button: "Random"
    regular_wikipedia: "View this page on regular Wikipedia"
    perm_stop_redirect: "Permanently disable mobile site"
    copyright: "Text is available under the <a href='http://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License'>Creative Commons Attribution/Share-Alike License</a>; additional terms may apply. See <a href='http://wikimediafoundation.org/wiki/Terms_of_Use'>Terms of Use</a> for details. Wikipedia® is a registered trademark of the <a href='http://www.wikimediafoundation.org/'>Wikimedia Foundation, Inc.</a>, a non-profit organization."
  selectors:
    article_of_the_day: "#mp-tfa"
    news_items: "#mp-itn"

de: 
  main_page: "Wikipedia:Hauptseite"
  translations:
    go: "Los"
    search_results: "Suchergebnisse"
    no_article_found: "Es existiert kein Artikel"
    featured_article: "Artikel des Tages"
    in_the_news: "In den Nachrichten"
    home_button: "Start"
    random_button: "Zufall"
    copyright: "Der Text ist unter der <a class='internal' href='http://de.wikipedia.org/wiki/Wikipedia:Lizenzbestimmungen_Commons_Attribution-ShareAlike_3.0_Unported'>„Creative Commons Attribution/Share-Alike“-Lizenz</a> verfügbar; zusätzliche Bedingungen können anwendbar sein. Siehe die <a class='internal' href='http://wikimediafoundation.org/wiki/Terms_of_Use'>Nutzungsbedingungen</a> für Einzelheiten. Wikipedia® ist eine eingetragene Marke der Wikimedia Foundation Inc."
  selectors:
    article_of_the_day: "#hauptseite-artikel .inhalt"
    news_items: "#hauptseite-nachrichten .inhalt"

fr:
  main_page: "Accueil"
  translations:
    go: "Consulter"
    search_results: "Résultats de la recherche"
    no_article_found: "Aucun titre de page ne correspond à la recherche"
    featured_article: "Lumière sur..."
    in_the_news: "Actualités et événements"
    random_article: "Un article au hasard"
    random_article_notice: "Vous avez été envoyé ici car vous avez cliqué sur le logo de la page principale, cliquer à nouveau sur le W pour revenir en [arrière|à la page précédente]"
    link_to_wikipedia: "Regardez cette page sur son site d'origine"
    copyright: "<a class='internal' href='/wiki/Wikip%C3%A9dia:Droit_d%27auteur' title='Droit d'auteur'>Droit d'auteur</a> : Les textes sont disponibles sous <a href='http://creativecommons.org/licenses/by-sa/3.0/'>licence Creative Commons attribution partage à l’identique</a> ; d’autres termes peuvent s’appliquer. Voyez les <a href='http://wikimediafoundation.org/wiki/Terms_of_Use'>termes d’utilisation</a> pour plus de détails. Wikipedia® est une marque déposée de la <a href='http://wikimediafoundation.org/wiki/Accueil' title='Wikimedia Foundation'>Wikimedia Foundation, Inc.</a>, organisation de bienfaisance régie par le paragraphe <a class='internal' href='/wiki/501c' title='501c'>501(c)(3)</a> du code fiscal des États-Unis."
  selectors:
    article_of_the_day: "#bodyContent table tr:nth-child(3) td:nth-child(3) div:nth-child(1) .accueil_contenu"
    news_items: "#bodyContent table tr:nth-child(3) td:nth-child(3) div:nth-child(3) .accueil_contenu"
ja: 
  main_page: "メインページ"
  translations:
    go: "表示"
    search_results: "検索結果"
    no_article_found: "検索した名称のページは存在しませんでした"
    featured_article: "秀逸な記事"
    in_the_news: "新着記事"
    random_article: "つまみ読み"
    copyright: "テキストは<a href='http://creativecommons.org/licenses/by-sa/3.0/deed.ja'>クリエイティブ・コモンズ 表示-継承ライセンス</a>の下で利用可能です。追加の条件が適用される場合があります。詳細は<a href='http://wikimediafoundation.org/wiki/Terms_of_Use'>利用規約</a>を参照してください"
  selectors:
    article_of_the_day: "#bodyContent table:nth-child(8) td:nth-child(1) div:nth-child(3)"
    news_items:         "#bodyContent table:nth-child(8) td:nth-child(1) div:nth-child(6)"
pl: 
  main_page: "Strona_główna"
  translations: 
    go: "Przejdź" 
    search_results: "Wyniki wyszukiwania"
    no_article_found: "No Article Found"
    featured_article: "Today's Featured Article"
    in_the_news: "In The News"
    random_article: "Random Article"
    copyright: "Tekst udostępniany na <a href='http://creativecommons.org/licenses/by-sa/3.0/deed.pl'>licencji Creative Commons: uznanie autorstwa, na tych samych warunkach</a>, z możliwością obowiązywania dodatkowych ograniczeń. Zobacz szczegółowe informacje o <a href='http://wikimediafoundation.org/wiki/Terms_of_Use'>warunkach korzystania</a>."
  selectors:
    article_of_the_day: "div[style='padding: 5px; font-size: 9pt;']"
    news_items: "#bodyContent :nth-child(7) :nth-child(5)"
es:
  main_page: "Wikipedia:Portada"
  translations:
    go: "Ir"
    search_results: "Resultados de la búsqueda"
    no_article_found: "No hay coincidencias"
    featured_article: "Artículo destacado"
    in_the_news: "Actualidad"
    random_article: "Página aleatoria"
  selectors:
    article_of_the_day: "#bodyContent table:nth-child(6) table:nth-child(1) tr:nth-child(2)"
    news_items: "#bodyContent table:nth-child(6) table:nth-child(1) tr:nth-child(8)"
pt:
  main_page: "Página_principal"
  translations:
    go: "Ir"
    search_results: "Resultados de pesquisa"
    no_article_found: "Não Encontrado artigo"
    featured_article: "Artigo em destaque"
    in_the_news: "Eventos recentes"
    random_article: "Página aleatória"
  selectors:
    article_of_the_day: "#bodyContent table:nth-child(1) tr:nth-child(2)"
    news_items: "#bodyContent div table:nth-child(1) tr:nth-child(2)"
nl: 
  main_page: "Hoofdpagina"
  translations:
    go: "Artikel"
    search_results: "Zoekresultaten"
    no_article_found: "Geen resultaten gevonden"
    featured_article: "Uitgelicht"
    in_the_news: "Actueel"
    in_the_news_alt: "In het nieuws"
    random_article: "Willekeurige pagina"
  selectors:
    article_of_the_day: "tr:nth-child(4) table.radius:nth-child(1) tr:nth-child(3) td:nth-child(1) div:nth-child(1)"
    news_items: "tr:nth-child(4) table.radius:nth-child(2) tr:nth-child(3) td:nth-child(1) div:nth-child(1)"
    
fi:
  main_page: "Wikipedia:Etusivu"
  translations:
    go: "Siirry"
    search_results: "Etsi"
    no_article_found: "Artikkelia ei löytynyt"
    featured_article: "Suositeltu artikkeli"
    in_the_news: "Ajankohtaista"
    random_article: "Satunnainen artikkeli"
  selectors:
    article_of_the_day: "#bodyContent table tr:nth-child(2) td:nth-child(1) div:nth-child(2) div:nth-child(2)"
    news_items: "#bodyContent table tr:nth-child(2) td:nth-child(2) div:nth-child(1) div:nth-child(2)"
it:
  main_page: "Pagina_principale"
  translations:
    go: "Vai"
    search_results: "Risultati della ricerca"
    no_article_found: "Nessuna corrispondenza"
    featured_article: "Vetrina"
    in_the_news: "Novità"
    random_article: "Una voce e caso"
  selectors:
    article_of_the_day: "#Vetrina ~ div"
    news_items: "a[id='Novit.C3.A0'] ~ div"
  
