#
#  ================= WIKIPEDIA MAIN PAGE REFERENCE ===================
#
# Wikipedia home pages have lots of different characteristics as each
# is maintained by their respective communities. This document is an
# attempt at bringing some order to that system. We are attempting to
# keep here functioning CSS selectors and Main_Page names for each
# of the major Wikipedia languages.
#
# ==== SELECTORS ====
#
# Selectors are CSS2 selectors that are used to identify common elements on different
# Wikipedia home pages.
#
# Each language can have any number of the following selectors.
# Listed is the key name *AND* the preferred selector
#
#       featured_article:       "#mp-tfa"
#       news_items:             "#mp-itn"
#       on_this_day:            "#mp-otd"
#       featured_picture:       "#mp-tfp"
#       facts:                  "#mp-dyk"
#       good_article:           "#mp-tfga"
#       quote_of_the_day:       "#mp-qotd"
#
#
# === AUTHOR ===
# 
#  This list was created and is maintained by Hampton Catlin (hcatlin@wikimedia.org)
#  Contact him with any issues.
#

--- 
en: 
  main_page: Main_Page
  selectors: &defaults
    featured_article: "#mp-tfa"
    news_items: "#mp-itn"
    #on_this_day: "#mp-otd"
    featured_picture: "#mp-tfp"
    #facts: "#mp-dyk"

de: 
  main_page: Wikipedia:Hauptseite
  selectors: 
    featured_article: "#hauptseite-artikel .inhalt"
    news_items: "#hauptseite-nachrichten .inhalt"

es: 
  main_page: Wikipedia:Portada
  selectors:
    featured_article: "#mp-tfa"
    news_items: "#mp-itn"
    on_this_day: "#mp-otd"
    featured_picture: "#mp-tfp"
    facts: "#mp-dyk"
    good_article: "#mp-tfga"
    quote_of_the_day: "#mp-qotd"

fr:
  main_page: Accueil
  selectors: 
    featured_article: "#accueil-lumieresur"
    news_items: "#accueil-actualite"
    facts: "#SaviezVous"
    featured_picture: "#ImageDuJour"

pl: 
  main_page: "Strona_g\xC5\x82\xC3\xB3wna"
  selectors: 
    featured_article: "#mp-tfa"
    news_items: "#mp-itn"
    on_this_day: "#mp-otd"
    featured_picture: "#mp-tfp"
    facts: "#mp-dyk"
    good_article: "#mp-tfga"
    quote_of_the_day: "#mp-qotd"
pt: 
  main_page: "P\xC3\xA1gina_principal"
  selectors: 
    featured_article: "#bodyContent table:nth-child(1) tr:nth-child(2)"
    news_items: "#bodyContent div table:nth-child(1) tr:nth-child(2)"
nl: 
  main_page: Hoofdpagina
  selectors: 
    featured_article: "#mp-tfa"
    news_items: "#mp-itn"
    on_this_day: "#mp-otd"
    featured_picture: "#mp-tfp"
    facts: "#mp-dyk"
    good_article: "#mp-tfga"
    quote_of_the_day: "#mp-qotd"

fi: 
  main_page: Wikipedia:Etusivu
  selectors: 
    featured_article: "#bodyContent table tr:nth-child(2) td:nth-child(1) div:nth-child(2) div:nth-child(2)"
    news_items: "#bodyContent table tr:nth-child(2) td:nth-child(2) div:nth-child(1) div:nth-child(2)"

cs:
  main_page: "Hlavn%C3%AD_strana"
  selectors:
    featured_article: "#mp-tfa"
    news_items: "#mp-itn"
    #on_this_day: "#mp-otd"
    featured_picture: "#mp-tfp"

he:
  main_page: "%D7%A2%D7%9E%D7%95%D7%93_%D7%A8%D7%90%D7%A9%D7%99"
  selectors:
    featured_article: "#mp-tfa"
    news_items: "#mp-itn"
    featured_picture: "#mp-tfp"
    facts: "#mp-dyk"
    on_this_day: "#mp-otd"

nn:
  main_page: "Hovudside"
  selectors:
    featured_article: "#mp-tfa"
    on_this_day: "#mp-otd"
    facts: "#mp-dyk"

it: 
  mobile_main_page: Pagina_Principale_%28mobile%29
sv:
  mobile_main_page: Portal:Huvudsida_%28mobil%29
da:
  mobile_main_page: Forside_(mobil)
et:
  mobile_main_page: Portaal:Esileht_(mobiilseadmetele)
ml:
  mobile_main_page: %E0%B4%95%E0%B4%B5%E0%B4%BE%E0%B4%9F%E0%B4%82%3A%E0%B4%AA%E0%B5%8D%E0%B4%B0%E0%B4%A7%E0%B4%BE%E0%B4%A8%E0%B4%A4%E0%B4%BE%E0%B5%BE_%28%E0%B4%AE%E0%B5%8A%E0%B4%AC%E0%B5%88%E0%B5%BD%29
ar:
  mobile_main_page: %D8%A7%D9%84%D8%B5%D9%81%D8%AD%D8%A9_%D8%A7%D9%84%D8%B1%D8%A6%D9%8A%D8%B3%D9%8A%D8%A9_%28%D9%86%D9%82%D8%A7%D9%84%29
th:
  mobile_main_page: %E0%B8%AA%E0%B8%96%E0%B8%B2%E0%B8%99%E0%B8%B5%E0%B8%A2%E0%B9%88%E0%B8%AD%E0%B8%A2:%E0%B8%AB%E0%B8%99%E0%B9%89%E0%B8%B2%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81_%28%E0%B9%82%E0%B8%A1%E0%B8%9A%E0%B8%B2%E0%B8%A2%E0%B8%A5%E0%B9%8C%29
vi:
  mobile_main_page: Wikipedia:Trang_Ch%C3%ADnh/Di_%C4%91%E1%BB%99ng
zh:
  mobile_main_page: Portal:%E7%A7%BB%E5%8A%A8%E7%89%88%E9%A6%96%E9%A1%B5
bn:
  mobile_main_page: %E0%A6%AA%E0%A7%8D%E0%A6%B0%E0%A6%AC%E0%A7%87%E0%A6%B6%E0%A6%A6%E0%A7%8D%E0%A6%AC%E0%A6%BE%E0%A6%B0%3A%E0%A6%AA%E0%A7%8D%E0%A6%B0%E0%A6%A7%E0%A6%BE%E0%A6%A8_%E0%A6%AA%E0%A6%BE%E0%A6%A4%E0%A6%BE_%28%E0%A6%AE%E0%A7%8B%E0%A6%AC%E0%A6%BE%E0%A6%87%E0%A6%B2%29
ar:
  mobile_main_page: %D8%A7%D9%84%D8%B5%D9%81%D8%AD%D8%A9_%D8%A7%D9%84%D8%B1%D8%A6%D9%8A%D8%B3%D9%8A%D8%A9_(%D9%86%D9%82%D8%A7%D9%84)
hu:
  mobile_main_page: Kezd%C5%91lap%2FMobil
el:
  mobile_main_page: %CE%A0%CF%8D%CE%BB%CE%B7:%CE%9A%CF%8D%CF%81%CE%B9%CE%B1/Mobile
  
ca:
  main_page: Portada
  selectors:
    featured_article: "#mp-tfa"
    facts: "#mp-dyk"
    on_this_day: "#mp-otd"
    news_items: "#mp-itn"
    featured_picture: "#mp-tfp"

mr:
  homepage: "%E0%A4%AE%E0%A5%81%E0%A4%96%E0%A4%AA%E0%A5%83%E0%A4%B7%E0%A5%8D%E0%A4%A0"
  selectors:
    featured_article: "#mp-tfa"
    facts: "#mp-dyk"
    on_this_day: "#mp-otd"
    featured_picture: "#mp-tfp"
