#
#  ================= WIKIPEDIA MAIN PAGE REFERENCE ===================
#
# Wikipedia home pages have lots of different characteristics as each
# is maintained by their respective communities. This document is an
# attempt at bringing some order to that system. We are attempting to
# keep here functioning CSS selectors and Main_Page names for each
# of the major Wikipedia languages.
#
# ==== SELECTORS ====
#
# Selectors are CSS2 selectors that are used to identify common elements on different
# Wikipedia home pages.
#
# Each language can have any number of the following selectors.
# Listed is the key name *AND* the preferred selector
#
#       featured_article:       "#mp-tfa"
#       news_items:             "#mp-itn"
#       on_this_day:            "#mp-otd"
#       featured_picture:       "#mp-tfp"
#       facts:                  "#mp-dyk"
#       good_article:           "#mp-tfga"
#       quote_of_the_day:       "#mp-qotd"
#
#
# === AUTHOR ===
# 
#  This list was created and is maintained by Hampton Catlin (hcatlin@wikimedia.org)
#  Contact him with any issues.
#

--- 
en: 
  main_page: Main_Page
  selectors: &defaults
    featured_article: "#mp-tfa"
    news_items: "#mp-itn"
    #on_this_day: "#mp-otd"
    featured_picture: "#mp-tfp"
    #facts: "#mp-dyk"

de: 
  main_page: Wikipedia:Hauptseite
  selectors: 
    featured_article: "#hauptseite-artikel .inhalt"
    news_items: "#hauptseite-nachrichten .inhalt"

ru:
  main_page: Заглавная_страница
  selectors:
    featured_article: "#mp-tfa"
    facts: "#mp-dyk"

es: 
  main_page: Wikipedia:Portada
  selectors:
    featured_article: "#mp-tfa"
    news_items: "#mp-itn"
    on_this_day: "#mp-otd"
    featured_picture: "#mp-tfp"
    facts: "#mp-dyk"
    good_article: "#mp-tfga"
    quote_of_the_day: "#mp-qotd"

fr:
  main_page: Accueil
  selectors: 
    featured_article: "#accueil-lumieresur"
    news_items: "#accueil-actualite"
    facts: "#SaviezVous"
    featured_picture: "#ImageDuJour"

pl: 
  main_page: "Strona_g\xC5\x82\xC3\xB3wna"
  selectors: 
    featured_article: "#mp-tfa"
    news_items: "#mp-itn"
    on_this_day: "#mp-otd"
    featured_picture: "#mp-tfp"
    facts: "#mp-dyk"
    good_article: "#mp-tfga"
    quote_of_the_day: "#mp-qotd"
pt: 
  main_page: "P\xC3\xA1gina_principal"
  selectors: 
    featured_article: "#bodyContent table:nth-child(1) tr:nth-child(2)"
    news_items: "#bodyContent div table:nth-child(1) tr:nth-child(2)"
nl: 
  main_page: Hoofdpagina
  selectors: 
    featured_article: "#mp-tfa"
    news_items: "#mp-itn"
    on_this_day: "#mp-otd"
    featured_picture: "#mp-tfp"
    facts: "#mp-dyk"
    good_article: "#mp-tfga"
    quote_of_the_day: "#mp-qotd"

fi: 
  main_page: Wikipedia:Etusivu
  selectors: 
    featured_article: "#bodyContent table tr:nth-child(2) td:nth-child(1) div:nth-child(2) div:nth-child(2)"
    news_items: "#bodyContent table tr:nth-child(2) td:nth-child(2) div:nth-child(1) div:nth-child(2)"

cs:
  main_page: "Hlavn%C3%AD_strana"
  selectors:
    featured_article: "#mp-tfa"
    news_items: "#mp-itn"
    #on_this_day: "#mp-otd"
    featured_picture: "#mp-tfp"
    
eo:
  main_page: Vikipedio%3a%c4%88efpa%c4%9do
  selectors:
    featured_article: "#mp-tfa"
    news_items: "#mp-itn"

he:
  main_page: "%D7%A2%D7%9E%D7%95%D7%93_%D7%A8%D7%90%D7%A9%D7%99"
  selectors:
    featured_article: "#mp-tfa"
    news_items: "#mp-itn"
    featured_picture: "#mp-tfp"
    facts: "#mp-dyk"
    on_this_day: "#mp-otd"

nn:
  main_page: "Hovudside"
  selectors:
    featured_article: "#mp-tfa"
    on_this_day: "#mp-otd"
    facts: "#mp-dyk"

bh:
  main_page: "%E0%A4%AA%E0%A4%B9%E0%A4%BF%E0%A4%B2%E0%A4%95%E0%A4%BE_%E0%A4%AA%E0%A4%A8%E0%A5%8D%E0%A4%A8%E0%A4%BE"
  selectors:
    featured_article: "#mp-featured_article"
    featured_picture: "#mp-featured_picture"
br:
  main_page: Degemer
  selectors:
    featured_article: "#mp-tfa"
    news_items: "#mp-itn"
    on_this_day: "#mp-otd"
    featured_picture: "#mp-tfp"
    facts: "#mp-dyk"
    good_article: "#mp-tfga"
    quote_of_the_day: "#mp-qotd"

tr:
  mobile_main_page: Vikipedi:Ana_Sayfa_%28mobil%29
it: 
  mobile_main_page: Pagina_Principale_%28mobile%29
sv:
  mobile_main_page: Portal:Huvudsida_%28mobil%29
'no':
  mobile_main_page: Portal:Forside_%28mobil%29
da:
  mobile_main_page: Forside (mobil)
et:
  mobile_main_page: Portaal:Esileht_(mobiilseadmetele)
el:
  mobile_main_page: %CE%A0%CF%8D%CE%BB%CE%B7:%CE%9A%CF%8D%CF%81%CE%B9%CE%B1/Mobile
ml:
  mobile_main_page: %E0%B4%95%E0%B4%B5%E0%B4%BE%E0%B4%9F%E0%B4%82%3A%E0%B4%AA%E0%B5%8D%E0%B4%B0%E0%B4%A7%E0%B4%BE%E0%B4%A8%E0%B4%A4%E0%B4%BE%E0%B5%BE_%28%E0%B4%AE%E0%B5%8A%E0%B4%AC%E0%B5%88%E0%B5%BD%29
ar:
  mobile_main_page: %D8%A7%D9%84%D8%B5%D9%81%D8%AD%D8%A9_%D8%A7%D9%84%D8%B1%D8%A6%D9%8A%D8%B3%D9%8A%D8%A9_%28%D9%86%D9%82%D8%A7%D9%84%29
th:
  mobile_main_page: %E0%B8%AA%E0%B8%96%E0%B8%B2%E0%B8%99%E0%B8%B5%E0%B8%A2%E0%B9%88%E0%B8%AD%E0%B8%A2:%E0%B8%AB%E0%B8%99%E0%B9%89%E0%B8%B2%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81_%28%E0%B9%82%E0%B8%A1%E0%B8%9A%E0%B8%B2%E0%B8%A2%E0%B8%A5%E0%B9%8C%29
vi:
  mobile_main_page: Wikipedia:Trang_Ch%C3%ADnh/Di_%C4%91%E1%BB%99ng
zh:
  mobile_main_page: Portal:%E6%89%8B%E6%9C%BA%E7%89%88%E9%A6%96%E9%A1%B5
id:
  mobile_main_page: Portal:Halaman%20Utama%20(seluler)
hsb:
  mobile_main_page: H%c5%82owna strona
uk:
  mobile_main_page: %D0%93%D0%BE%D0%BB%D0%BE%D0%B2%D0%BD%D0%B0_%D1%81%D1%82%D0%BE%D1%80%D1%96%D0%BD%D0%BA%D0%B0/Wikipedia_Mobile
dsb:
  mobile_main_page: G%c5%82owny bok
bn:
  mobile_main_page: %E0%A6%AA%E0%A7%8D%E0%A6%B0%E0%A6%AC%E0%A7%87%E0%A6%B6%E0%A6%A6%E0%A7%8D%E0%A6%AC%E0%A6%BE%E0%A6%B0%3A%E0%A6%AA%E0%A7%8D%E0%A6%B0%E0%A6%A7%E0%A6%BE%E0%A6%A8_%E0%A6%AA%E0%A6%BE%E0%A6%A4%E0%A6%BE_%28%E0%A6%AE%E0%A7%8B%E0%A6%AC%E0%A6%BE%E0%A6%87%E0%A6%B2%29
ar:
  mobile_main_page: %D8%A7%D9%84%D8%B5%D9%81%D8%AD%D8%A9_%D8%A7%D9%84%D8%B1%D8%A6%D9%8A%D8%B3%D9%8A%D8%A9_(%D9%86%D9%82%D8%A7%D9%84)
hu:
  mobile_main_page: Kezd%C5%91lap%2FMobil
el:
  mobile_main_page: %CE%A0%CF%8D%CE%BB%CE%B7:%CE%9A%CF%8D%CF%81%CE%B9%CE%B1/Mobile
ja:
  mobile_main_page: %E3%83%A1%E3%82%A4%E3%83%B3%E3%83%9A%E3%83%BC%E3%82%B8_%28%E3%83%A2%E3%83%90%E3%82%A4%E3%83%AB%E7%89%88%29
ko:
  mobile_main_page: %EC%9C%84%ED%82%A4%EB%B0%B1%EA%B3%BC:%EB%8C%80%EB%AC%B8_%28%EB%AA%A8%EB%B0%94%EC%9D%BC%29
krc:
  mobile_main_page: %D0%92%D0%B8%D0%BA%D0%B8%D0%BF%D0%B5%D0%B4%D0%B8%D1%8F%3A%D0%91%D0%B0%D1%88_%D0%B1%D0%B5%D1%82_(%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB)
xal:
  mobile_main_page: %d0%ad%d0%ba%d0%bb%d1%86%d0%b8%d0%bd_%d0%a5%d0%b0%d0%bb%d1%85
gl:
  mobile_main_page: Wikipedia:Galipedia_m%C3%B3bil
tt:
  mobile_main_page: %D0%91%D0%B0%D1%88%20%D0%B1%D0%B8%D1%82
ro:
  mobile_main_page: Portal:Mobil
ka:
  mobile_main_page: %E1%83%9E%E1%83%9D%E1%83%A0%E1%83%A2%E1%83%90%E1%83%9A%E1%83%98%3A%E1%83%9B%E1%83%97%E1%83%90%E1%83%95%E1%83%90%E1%83%A0%E1%83%98_%E1%83%92%E1%83%95%E1%83%94%E1%83%A0%E1%83%93%E1%83%98_%28%E1%83%9B%E1%83%9D%E1%83%91%E1%83%98%E1%83%9A%E1%83%A3%E1%83%A0%E1%83%98%29
krc:
  mobile_main_page: %D0%92%D0%B8%D0%BA%D0%B8%D0%BF%D0%B5%D0%B4%D0%B8%D1%8F%3A%D0%91%D0%B0%D1%88%20%D0%B1%D0%B5%D1%82%20%28%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%29
ca:
  main_page: Portada
  selectors:
    featured_article: "#mp-tfa"
    facts: "#mp-dyk"
    on_this_day: "#mp-otd"
    news_items: "#mp-itn"
    featured_picture: "#mp-tfp"

si:
  main_page: "%E0%B6%B8%E0%B7%94%E0%B6%BD%E0%B7%8A_%E0%B6%B4%E0%B7%92%E0%B6%A7%E0%B7%94%E0%B7%80"
  selectors: 
    featured_article: "#mp-tfa"
    featured_picture: "#mp-tfp"

mr:
  homepage: "%E0%A4%AE%E0%A5%81%E0%A4%96%E0%A4%AA%E0%A5%83%E0%A4%B7%E0%A5%8D%E0%A4%A0"
  selectors:
    featured_article: "#mp-tfa"
    facts: "#mp-dyk"
    on_this_day: "#mp-otd"
    featured_picture: "#mp-tfp"