en: 
  main_page: "Main_Page"
  translations:
    go: "Go"
    search_results: "Search Results"
    no_article_found: "No Article Found"
    featured_article: "Today's Featured Article"
    in_the_news: "In The News"
    random_article: "Random Article"
  selectors:
    article_of_the_day: "#mp-tfa"
    news_items: "#mp-itn"
de: 
  main_page: "Wikipedia:Hauptseite"
  translations:
    go: "Artikel"
    search_results: "Suchergebnisse"
    no_article_found: "Es existiert kein Artikel"
    featured_article: "Artikel des Tages"
    in_the_news: "In den Nachrichten"
    random_article: "Random Article"
  selectors:
    article_of_the_day: "#hauptseite-artikel .inhalt"
    news_items: "#hauptseite-nachrichten .inhalt"
fr:
  main_page: "Accueil"
  translations:
    go: "Consulter"
    search_results: "Search Results"
    no_article_found: "No Article Found"
    featured_article: "Today's Featured Article"
    in_the_news: "In The News"
    random_article: "Random Article"
  selectors:
    article_of_the_day: "#bodyContent table tr:nth-child(3) td:nth-child(3) div:nth-child(1) .accueil_contenu"
    news_items: "#bodyContent table tr:nth-child(3) td:nth-child(3) div:nth-child(3) .accueil_contenu"
ja: 
  main_page: "メインページ"
  translations:
    go: "表示"
    search_results: "Search Results"
    no_article_found: "No Article Found"
    featured_article: "Today's Featured Article"
    in_the_news: "In The News"
    random_article: "Random Article"
pl: 
  main_page: "Strona_główna"
  translations: 
    go: "Przejdź" 
    search_results: "Search Results"
    no_article_found: "No Article Found"
    featured_article: "Today's Featured Article"
    in_the_news: "In The News"
    random_article: "Random Article"
  selectors:
    article_of_the_day: "div[style='padding: 5px; font-size: 9pt;']"
    news_items: "#bodyContent :nth-child(7) :nth-child(5)"
es:
  main_page: "Wikipedia:Portada"
  translations:
    go: "Ir"
    search_results: "Buscar"
    no_article_found: "No hay coincidencias"
    featured_article: "Artículo destacado"
    in_the_news: "Actualidad"
    random_article: "Página aleatoria"
  selectors:
    article_of_the_day: "#bodyContent table:nth-child(6) table:nth-child(1) tr:nth-child(2)"
    news_items: "#bodyContent table:nth-child(6) table:nth-child(1) tr:nth-child(8)"

